version: "3.9"

networks:
  prefect-network:
    name: prefect-network
    ipam:
      driver: default
      config:
          - subnet: "192.168.0.0/24"
            gateway: "192.168.0.1"

services:
  prefect-server:
    image: ${SERVER_IMAGE}
    volumes:
      - prefect_data:/root/.prefect
      - prefect_flows:/opt/prefect/flows
    ports:
      - 4200:4200
    networks:
      - prefect-network
    env_file:
      - .env
  prefect-agent:
    image: ${AGENT_IMAGE}
    depends_on:
      - prefect-server
    networks:
      - prefect-network
    environment:
      - PREFECT_API_URL=http://192.168.0.2:4200/api

volumes:
  prefect_data:
  prefect_flows:
