version: "3.9"

networks:
  prefect-network:
    name: prefect-network

services:
  prefect-server:
    image: ny-taxi-prefect-server:v1
    entrypoint: [ "prefect", "server", "start" ]
    restart: always
    volumes:
      - prefect_data:/root/.prefect
      - prefect_flows:/flows
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://prefect-server:4200/api
    ports:
      - 4200:4200
    networks:
      - prefect-network
  prefect-agent:
    image: ny-taxi-prefect-server:v1
    entrypoint: [ "prefect", "agent", "start", "-q", "default" ]
    depends_on:
      - prefect-server
    networks:
      - prefect-network
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
volumes:
  prefect_data:
  prefect_flows:
