name: 'dbt_nytaxi'
version: '1.0.0'
config-version: 2

profile: 'bq-dbt-ny-taxi'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets: 
  - "target"
  - "dbt_packages"

models:
  dbt_nytaxi:
    staging:
      materialized: view
    core:
      materialized: table
